name: leafloom
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.6
  firebase_cloud_firestore: ^4.17.3
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/images/app-logo.png
  image_dark: assets/images/app-logo.png
  android: true
  android_12:
    image: assets/images/app-logo.png
    image_dark: assets/images/app-logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/banner/
    - assets/images/produk/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Lato-SemiBold.ttf
          weight: 600
          style: normal
