name: leafloom
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.1.0
 
  # State management
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_native_splash:
  color: '#FFFFFF'
  image: leafloomapp\assets\image\appLogo.png
  android: true
  ios: true
  web: true
  android_12: true
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/banner/
    - assets/images/produk/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Lato-SemiBold.ttf
          weight: 600
          style: normal
