// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMDvWDglraOA8wJc5CDcAIv284tqxye0U',
    appId: '1:32923809876:web:78a88caba95307cd71d5c1',
    messagingSenderId: '32923809876',
    projectId: 'leafloom-dbba2',
    authDomain: 'leafloom-dbba2.firebaseapp.com',
    storageBucket: 'leafloom-dbba2.appspot.com',
    measurementId: 'G-FT1247D49C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYAIoBMLUP7j1PeDC60e8VCO0iyjBoFo',
    appId: '1:32923809876:android:d103b52c41b7e83871d5c1',
    messagingSenderId: '32923809876',
    projectId: 'leafloom-dbba2',
    storageBucket: 'leafloom-dbba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDschtwu0AOAIk0m3FE9K5_vN9EH4LQQF0',
    appId: '1:32923809876:ios:aa238136ade815cd71d5c1',
    messagingSenderId: '32923809876',
    projectId: 'leafloom-dbba2',
    storageBucket: 'leafloom-dbba2.appspot.com',
    iosBundleId: 'com.example.leafloomapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDschtwu0AOAIk0m3FE9K5_vN9EH4LQQF0',
    appId: '1:32923809876:ios:aa238136ade815cd71d5c1',
    messagingSenderId: '32923809876',
    projectId: 'leafloom-dbba2',
    storageBucket: 'leafloom-dbba2.appspot.com',
    iosBundleId: 'com.example.leafloomapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMDvWDglraOA8wJc5CDcAIv284tqxye0U',
    appId: '1:32923809876:web:8a80004bec9a397671d5c1',
    messagingSenderId: '32923809876',
    projectId: 'leafloom-dbba2',
    authDomain: 'leafloom-dbba2.firebaseapp.com',
    storageBucket: 'leafloom-dbba2.appspot.com',
    measurementId: 'G-K8JCZP433V',
  );
}
